-- Crear la tabla de donaciones para registrar las transacciones de Stripe.
CREATE TABLE IF NOT EXISTS public.donations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) NOT NULL,
    amount numeric NOT NULL,
    currency text NOT NULL,
    stripe_payment_intent_id text UNIQUE NOT NULL,
    status text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Crear la vista de rankings de DJs, sumando las donaciones exitosas.
CREATE OR REPLACE VIEW public.dj_rankings AS
SELECT
    d.user_id,
    dp.stage_name AS dj_name,
    SUM(d.amount) AS total_donations
FROM
    public.donations d
JOIN
    public.dj_profiles dp ON d.user_id = dp.user_id
WHERE
    d.status = 'succeeded'
GROUP BY
    d.user_id,
    dp.stage_name
ORDER BY
    total_donations DESC;