// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rwtropleacbosxcauyht.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3dHJvcGxlYWNib3N4Y2F1eWh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MDMzMTcsImV4cCI6MjA2OTM3OTMxN30.YZ1KiGr-OuN2ScXJEL5b_kkN3tAOwryPFffALm91F_c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});